### ISSUE TITLE
How to get the HTML inside a node?

### ISSUE THREAD

**Issue by newk5** [digitalfondue/jfiveparse#32]
For example, once I have a node I can do Node#getTextContent() and I get the text content but how can I get the actual full HTML?
Imagine this:
```html
<div class="myDiv">hello</div>
```
When I do Node#getTextContent() I get "hello", but I want to get:  ``<div class="myDiv">hello</div>``

How can I achieve this?

**Comment by syjer** [comment]
hi @newk5 , you can call node.getOuterHtml()

**Comment by newk5** [comment]
> hi @newk5 , you can call node.getOuterHtml()

Hmm I dont see this method inside the Node class. This is my code: 
```java
NodeMatcher matcher = Selector.select().id("mp-dyk-h2").toMatcher();
  Node n =doc.getAllNodesMatching(matcher).stream().findFirst().get();
```

**Comment by syjer** [comment]
@newk5  it's a method which is part of the Element class.

If the node is an Element, you can cast to it.

Alternatively, you can simply call the static method JFiveParse.serialize(node); (see https://github.com/digitalfondue/jfiveparse/blob/ed38ca53c3ade23e051662772333dfe7484fcc49/src/main/java/ch/digitalfondue/jfiveparse/JFiveParse.java#L102 )

**Comment by newk5** [comment]
Oh I see, thanks, its working now 👍
